---
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: mern-k8s-db
  labels:
    app: mern-k8s
    component: db
spec:
  members: 2
  type: ReplicaSet
  version: "4.4.4"
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: mernuser
      db: admin
      passwordSecretRef: # a reference to the secret that will be used to generate the user's password
        name: mdb-community-password
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
        - name: readWriteAnyDatabase
          db: admin
      scramCredentialsSecretName: mdb-secret
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib
---
apiVersion: v1
kind: Secret
metadata:
  name: mdb-community-password
type: Opaque
stringData:
  password: mern-k8s-password
